# Generated by Django 6.0.6 on 2026-08-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgets',
            name='last_alert_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
