# Generated by Django 6.0.7 on 2026-08-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='completed_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
