# Generated by Django 6.0.7 on 2026-08-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_savingsgoal_completed_notification_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_savings', to='goals.savingsgoal')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('goal', 'month')},
            },
        ),
    ]
